POST http://localhost:8080/login
###

GET http://localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzQyMDkwNDd9.5ZBdWTDTacCEcHrbsD7QiRDyidtllt9Poj7ZmC_hv_8
###

POST http://localhost:8080/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzQxOTY0NjZ9.wvsT-_c5ISarhAtlGQaLKrmS4isngtKL4ugfj74EU30

{
  "id": "4",
  "title": "The Godfather",
  "author": "Mario Puzo"
}
###

DELETE http://localhost:8080/books/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzQxOTY0NjZ9.wvsT-_c5ISarhAtlGQaLKrmS4isngtKL4ugfj74EU30
###
